font:
  size: 11
  normal:
    family: Termsyn Mod
    style: Regular
  bold:
    family: Termsyn Mod
    style: Bold
  italic:
    family: Termsyn Mod
    style: Italic
colors:
  normal:
    black: "#2e2e2e"
    blue: "#398cff"
    cyan: "#7eabff"
    green: "#7ff0be"
    magenta: "#fe79f3"
    red: "#e27585"
    white: "#fbfdff"
    yellow: "#dfe0a3"
  bright:
    black: "#9ea1a5"
    blue: "#14aafe"
    cyan: "#bdd4ff"
    green: "#49feed"
    magenta: "#fe9df6"
    red: "#e98ca8"
    white: "#e3e7ed"
    yellow: "#e1f4c9"
  primary:
    background: "#1f1c20"
    foreground: "#d3d7dd"
window:
  opacity:
    0.75
  padding:
    x: 2
    y: 2
key_bindings:
  - key: Return
    mods: Alt|Shift
    action: SpawnNewInstance
