colors:
  primary:
    background: '0xcfcfd9'
    foreground: '0x1c2027'
  normal:
    black:   '0x192033'
    red:     '0xa62a3e'
    green:   '0x38912b'
    yellow:  '0xb27d12'
    blue:    '0x355c9a'
    magenta: '0x7c4f9f'
    cyan:    '0x258f8f'
    white:   '0x77858c'
  bright:
    black:   '0x666666'
    red:     '0xf04758'
    green:   '0x93c724'
    yellow:  '0xddb62b'
    blue:    '0x45a3e6'
    magenta: '0xc953ef'
    cyan:    '0x60c6c8'
    white:   '0xc0c0c0'
